In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
voc_size=10000#initialinzing the size of th dictionary

## One Hot Representation

In [4]:
onehot_repr=[one_hot(words,voc_size) for words in sent] #one_hot provides the index from dictionary
print(onehot_repr)

[[3101, 5945, 4189, 8489], [3101, 5945, 4189, 8476], [3101, 6448, 4189, 7492], [3540, 7990, 5748, 615, 3212], [3540, 7990, 5748, 615, 5267], [2718, 3101, 5143, 4189, 3811], [651, 7931, 7930, 615]]


## word embeddings representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #Whenever we pass anything to embedding layer,
                                                                  #all sentences should have same size for embedding to work properly
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8 #Fixing a length based on our choice
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)#pre adds zeroes in the front
print(embedded_docs)

[[   0    0    0    0 3101 5945 4189 8489]
 [   0    0    0    0 3101 5945 4189 8476]
 [   0    0    0    0 3101 6448 4189 7492]
 [   0    0    0 3540 7990 5748  615 3212]
 [   0    0    0 3540 7990 5748  615 5267]
 [   0    0    0 2718 3101 5143 4189 3811]
 [   0    0    0    0  651 7931 7930  615]]


In [10]:
dim=15 #dimensions(feature representation)

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))#(vocabulary size,dimension,sentence length)
model.compile('adam','mse')#adam optimizer,metrics=mean squared error

Metal device set to: Apple M1


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
#To see how words have been converted into featurized vectors

print(model.predict(embedded_docs))

2023-04-28 12:28:00.549197: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/1 [==============================] - 1s 545ms/step
[[[-0.01270229  0.0012197   0.02583391 -0.03941274 -0.04637166
    0.02180232  0.00965555 -0.00856559 -0.01064706 -0.01579307]
  [-0.01270229  0.0012197   0.02583391 -0.03941274 -0.04637166
    0.02180232  0.00965555 -0.00856559 -0.01064706 -0.01579307]
  [-0.01270229  0.0012197   0.02583391 -0.03941274 -0.04637166
    0.02180232  0.00965555 -0.00856559 -0.01064706 -0.01579307]
  [-0.01270229  0.0012197   0.02583391 -0.03941274 -0.04637166
    0.02180232  0.00965555 -0.00856559 -0.01064706 -0.01579307]
  [-0.04522891  0.0438792   0.03718394  0.04223767  0.00887668
    0.01246919 -0.01036717 -0.00151733 -0.00422549  0.03707388]
  [-0.04083807 -0.01797355 -0.02136686  0.02706868 -0.04335575
   -0.02553563  0.02532356  0.01846178 -0.01380085  0.04785562]
  [-0.03614682  0.004232   -0.00245354  0.01961667  0.01098979
    0.04863025 -0.00583246 -0.01451619  0.03875497  0.02095338]
  [-0.04073533  0.04575589  0.01751221 -0.00701834  0.0196

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3101, 5945, 4189, 8489], dtype=int32)

In [13]:
print(model.predict(embedded_docs[0])) #every word converted to vectors of 10 dimensions each

1/1 [==============================] - 0s 211ms/step
[[-0.01630785 -0.04026366  0.02847752 -0.0269576   0.04996909 -0.03866452
   0.02498596 -0.02077074 -0.04491105 -0.02337228]
 [-0.01630785 -0.04026366  0.02847752 -0.0269576   0.04996909 -0.03866452
   0.02498596 -0.02077074 -0.04491105 -0.02337228]
 [-0.01630785 -0.04026366  0.02847752 -0.0269576   0.04996909 -0.03866452
   0.02498596 -0.02077074 -0.04491105 -0.02337228]
 [-0.01630785 -0.04026366  0.02847752 -0.0269576   0.04996909 -0.03866452
   0.02498596 -0.02077074 -0.04491105 -0.02337228]
 [-0.0198541   0.01139752  0.01010191  0.002079   -0.02943106 -0.00522015
  -0.0113103  -0.01265835 -0.02197005  0.04854466]
 [ 0.02924358 -0.03633913 -0.00977372 -0.03410907  0.01156858 -0.0264598
   0.03458751 -0.01805938  0.01804424  0.0247411 ]
 [ 0.02769481 -0.01455057  0.03247886 -0.01243454 -0.02358117  0.00606849
   0.02842761  0.02691552  0.02459155  0.02547977]
 [-0.02500059  0.01926601 -0.01750021  0.04669738  0.00146605 -0.04905036